
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: team01-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-HomeController","number":25,"title":"Customize Home Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-4/pull/25"},{"author":{"id":"MDQ6VXNlcjI1NTMzNjIw","is_bot":false,"login":"Francisc0Leyva","name":"Francisco Justin Leyva"},"headRefName":"Justin-UniversityQueryService","number":23,"title":"Add University Query Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-4/pull/23"},{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-Joke-Controller","number":21,"title":"Add joke controller and tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-4/pull/21"}]
