
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: team01-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-READMEFixes","number":26,"title":"Add Updated Info to README","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-4/pull/26"},{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-HomeController","number":25,"title":"Customize Home Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-4/pull/25"},{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-PublicHoliday-Controller","number":24,"title":"Add PublicHoliday Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-4/pull/24"},{"author":{"id":"MDQ6VXNlcjI1NTMzNjIw","is_bot":false,"login":"Francisc0Leyva","name":"Francisco Justin Leyva"},"headRefName":"Justin-UniversityQueryService","number":23,"title":"Add University Query Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-4/pull/23"},{"author":{"id":"U_kgDOBXdYPQ","is_bot":false,"login":"aditiphatak","name":"Aditi Phatak"},"headRefName":"Aditi-Location","number":22,"title":"Add Location Service and Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-4/pull/22"},{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-Joke-Controller","number":21,"title":"Add joke controller and tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-4/pull/21"},{"author":{"id":"MDQ6VXNlcjQ2Njk2NDkw","is_bot":false,"login":"mitali-g","name":"Mitali Gaidhani"},"headRefName":"Mitali-ZipCode","number":19,"title":"Add ZipCode Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-4/pull/19"},{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-Joke","number":18,"title":"Add Joke Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-4/pull/18"}]
